django/testproject/catalogapp/urls.py
from django.urls import path
from catalogapp.views import ProductCatalogListView, ProductCreateView, SectionListView, PartKeyListView  # , get_page

app_name = 'catalogapp'

urlpatterns = [
    # path('', ProductCatalogListView.as_view(), name='product'),
    # path('', ProductCatalogListView.as_view(), name='main'),
    path('catalog-add/', ProductCreateView.as_view(), name='catalog_add'),
    # path('part/', SectionListView.as_view(), name='part'),
    path('', SectionListView.as_view(), name='product'),
    path('part/<str:pk>/', PartKeyListView.as_view(), name='part_key'),
    # path('get', get_page)


]

django/testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogapp.urls', namespace='catalogapp'))

]

django/testproject/catalogapp/models/part_list.py
from django.contrib.sites.managers import CurrentSiteManager
from django.contrib.sites.models import Site
from django.db import models

# Create your models here.
from catalogapp.models import ProductCatalog

from django.db.models import Manager


# class DeletedQuerySet(models.QuerySet):
#     def not_deleted(self):
#         return self.filter(deleted=False)
#
#
# class DeletedManager(Manager):
#     # def get_queryset(self):
#     #     return super().get_queryset().filter(deleted=False)
#
#     def get_queryset(self):
#         return DeletedQuerySet(self.model, using=self._db)
#
#     def not_deleted(self):
#         return self.get_queryset().not_deleted()


class Section(models.Model):
    """Модель раздела"""
    part_list = models.CharField(max_length=64, verbose_name="Раздел")
    # product_catalog = models.ForeignKey(ProductCatalog, on_delete=models.CASCADE, verbose_name="Раздел для пролуктов")
    # product_catalog = models.ManyToManyField(ProductCatalog, on_delete=models.CASCADE)
    product_catalog = models.ManyToManyField(ProductCatalog)
    # deleted = models.BooleanField(default=False, null=False)
    # objects = DeletedManager()
    # 36 мин., 50 мин.
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    # позволяет видеть разделы разных сайтов в админке
    # Получаем сайт эфект некорректная работа. Если "objects" стоит до "on_site" - видим все разделы в админке
    objects = Manager()
    on_site = CurrentSiteManager('site')
    # позволяет не менять код во view в работе с "objects", сайт эфект в админке разделы разбиты по сайтам
    # objects = CurrentSiteManager('site')

    def __str__(self):
        # return f'{self.part_list} {self.product_catalog.name}'
        return f'{self.part_list}'

    class Meta:
        verbose_name = 'Раздел товара'
        verbose_name_plural = 'Разделы товаров'

django/testproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}

</head>
<body>
{% block content %}
    {% include 'catalog.html' %}
{% endblock %}
</body>
</html>

django/testproject/templates/catalog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="buttonInLk">
        <a href="{% url 'catalogapp:catalog_add' %}">Добавить товар</a>
    </div>
    <div>
        <table class="table text-info">
            <tr class="bg-info">
                <th>Название товара</th>
                <th>Дата поступления</th>
                <th>Цена</th>
                <th>Единица измерения</th>
                <th>Наименование поставщика</th>
            </tr>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>{{ object.dates }}</td>
                    <td>{{ object.price }}</td>
                    <td>{{ object.unit }}</td>
                    <td>{{ object.name_supplier }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

django/testproject/templates/part.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="buttonInLk">
        <a href="{% url 'catalogapp:product' %}">В продукты</a>
        {#<a href="{% url 'catalogapp:part' %}">В разделы</a>#}
    </div>
    <div>
        {{ user.name }} {{ user.age }}
    </div>
    <div>
        <table class="table text-info">
            <tr class="bg-info">
                <th>Раздел</th>
                <th>Название товара</th>
                <th>Дата поступления</th>
                <th>Цена</th>
                <th>Единица измерения</th>
                <th>Наименование поставщика</th>
            </tr>
            {% for object in object_list %}
                {% for item in object.product_catalog.all %}
                    {# Для проверки: {{ item.name }}#}
                <tr>
                    <td>{{ object.part_list }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.dates }}</td>
                    <td>{{ item.price }}</td>
                    {% if item.unit == 'P' %}
                        <td>{{ 'шт' }}</td>
                    {% else %}
                        <td>{{ 'кг' }}</td>
                    {% endif %}
                    <td>{{ item.name_supplier }}</td>
                </tr>
                {% endfor %}
            {% endfor %}
        </table>
    </div>

{% endblock %}

django/testproject/templates/part_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="buttonInLk">
        <a href="{% url 'catalogapp:catalog_add' %}">Добавить товар</a>
<!--        <a href="{% url 'catalogapp:product' %}">В продукты</a>-->
    </div>
    <div>
{#        {{ site.name }}#}
        {{ user.name }} {{ user.age }}
    </div>
    <div>
        <table class="table text-info">
            <tr class="bg-info">
                <th>Удалён</th>
                <th>Раздел</th>
                <th>Название товара</th>
                <th>Дата поступления</th>
                <th>Цена</th>
                <th>Единица измерения</th>
                <th>Наименование поставщика</th>
                <th>Сайт</th>
            </tr>
            {#{{ queryset }}#}
{#        {{ object_list }}#}
            {% for object in object_list %}
{#                {% for item in object.product_catalog.all %}#}
                {% for item in object.product_catalog.all %}
                    {# Для проверки: {{ item.name }}#}
{#                    {% if item.deleted == False %}#}
                <tr>
{#                    <td>{{ object.part_list }}</td>#}
                    <td>{{ item.deleted }}</td>
                    <td><a href="{% url 'catalogapp:part_key' object.id %}">{{ object.part_list }}</a></td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.dates }}</td>
                    <td>{{ item.price }}</td>
                    {% if item.unit == 'P' %}
                        <td>{{ 'шт' }}</td>
                    {% else %}
                        <td>{{ 'кг' }}</td>
                    {% endif %}
                    <td>{{ item.name_supplier }}</td>
                    <td>{{ object.site.name }}</td>
                </tr>
{#                    {% endif %}#}
                {% endfor %}
            {% endfor %}
        </table>
    </div>

{% endblock %}

django/testproject/templates/updateCatalog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content">
        <div>
            <div class="buttonInLk">
                <a href="{% url 'catalogapp:product' %}">В товары</a>
            </div>

            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control" type="submit" value="Сохранить">
            </form>
        </div>
    </div>

{% endblock %}